### ISSUE TITLE
ToDo list (personal)

### ISSUE THREAD

**Issue by blaggacao** [input-output-hk/bitte#114]
# make sure no `tf clients` / `tf core` or `bitte deploy` has to be run under any circumstance to "customize" the cluster for an app
- [ ] move host volumes into `hydrate`
- [ ] move consul ACL / connect config into `hydrate`

# separation of concerns
- [ ] use `nomad` `node_class` to differentiate client groups instead of `meta` (for one, `node_class` are prominently shown in the UI)
- [ ] implement `bitte -l <node_class>` so that the blast radius of bitte opreations is limited to a node class
